name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/app/backend
            git pull origin main
            if [ -d "venv" ]; then
              source venv/bin/activate
            else
              python3 -m venv venv
              source venv/bin/activate
            fi
            pip install --upgrade pip
            pip install -r requirements.txt
            pm2 restart api || pm2 start app.py --name api --interpreter ./venv/bin/python
            pm2 save
            nginx -t && systemctl reload nginx
